version: '3' # Docker Compose version

services:
  db:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: edudallatorre
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    restart: unless-stopped

# Define the network soutside of the 'services' section
networks:
  db:
    driver: bridge

# Define the volume soutside of the 'services' section
volumes:
  db:
